{"objectID":316175,
"isHighlight":false,
"accessionNumber":"1988.277",
"accessionYear":"1988",
"isPublicDomain":true,
"primaryImage":"https://images.metmuseum.org/CRDImages/ao/original/vs1988_277.jpg",
"primaryImageSmall":"https://images.metmuseum.org/CRDImages/ao/web-large/vs1988_277.jpg",
"additionalImages":[],
"constituents":null,
"department":"Arts of Africa, Oceania, and the Americas",
"objectName":"Bottle",
"title":"Stirrup Spout Bottle: Mouse",
"culture":"Cupisnique",
"period":"",
"dynasty":"",
"reign":"",
"portfolio":"",
"artistRole":"",
"artistPrefix":"",
"artistDisplayName":"",
"artistDisplayBio":"",
"artistSuffix":"",
"artistAlphaSort":"",
"artistNationality":"",
"artistBeginDate":"",
"artistEndDate":"",
"artistGender":"",
"artistWikidata_URL":"",
"artistULAN_URL":"",
"objectDate":"12th–5th century B.C.",
"objectBeginDate":-1200,
"objectEndDate":-400,
"medium":"Ceramic",
"dimensions":"H. 8 × W. 1 3/8 × D. 1 1/4 in. (20.3 × 3.5 × 3.2 cm)",
"measurements":[{"elementName":"Overall","elementDescription":null,"elementMeasurements":{"Depth":3.1750064,"Height":20.32004,"Width":3.492507}}],
"creditLine":"Gift of Louis Slavitz, 1988",
"geographyType":"",
"city":"",
"state":"Chiclayo",
"county":"",
"country":"Peru",
"region":"",
"subregion":"",
"locale":"",
"locus":"",
"excavation":"",
"river":"",
"classification":"Ceramics-Containers",
"rightsAndReproduction":"",
"linkResource":"",
"metadataDate":"2021-03-10T04:39:49.39Z",
"repository":"Metropolitan Museum of Art, New York, NY",
"objectURL":"https://www.metmuseum.org/art/collection/search/316175",
"tags":[{"term":"Mice","AAT_URL":"http://vocab.getty.edu/page/aat/300250249","Wikidata_URL":"https://www.wikidata.org/wiki/Q39275"}],
"objectWikidata_URL":"",
"isTimelineWork":false,
"GalleryNumber":"357"}